language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-sklearn
script: "nosetests bayesian_bootstrap/tests"
